config/routes.rb
TestApp::Application.routes.draw do

  resources :catalogs do
    get :show_catalog, on: :collection
    get :show_catalog_first, on: :collection
  end 

  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show] 
    end
    root :to => 'categories#index', :via => :get
  end
  resources :lotadmin do
    get :lot_for_confirm, on: :collection
    get :confirmed, on: :member
  end 

  devise_for :users
  get "summury/totals"
  get "static_pages/faq"
  get "static_pages/about"
  get "static_pages/contacts"
  get "help", to: "static_pages#help"
  root to: 'StaticPages#about'
  resources :lotts do
    get :status, on: :member
  end
  resources :products
  resources :summury do
      get :totals, on: :member
      get :dolzhnik_notify, on: :member
  end 
  resources :users
  resources :orders do
    get :pay_for, on: :member
  end 
  resources :items
  resources :config_apps
  resources :payments do
    get :status, on: :member
    get :status_problem, on: :member
  end 
  resources :purchases
  resources :admin_items do
    get :status, on: :member
    get :payd, on: :member
    get :cancel, on: :member
    get :pay_for_override, on: :member
    get :na_sklade, on: :member
    get :list_pay, on: :collection  
    get :list_confirm, on: :collection
    get :list_payments, on: :collection
    get :list_lotts, on: :collection
    get :list_lotts_all, on: :collection
    get :list_items, on: :collection
    get :re_check, on: :member
    get :user_search, on: :collection
    get :user_card, on: :member
  end
  resources :lots do
    get :book, on: :member  
    get :debook, on: :member
  end 
  

end

app/controllers/admin_items_controller.rb
# -*- encoding : utf-8 -*-
class AdminItemsController < ApplicationController
    authorize_resource :class => false
    include ApplicationHelper
  
  def index
    @items = Item.paginate page: params[:page_full], order: 'created_at desc',
    per_page: 30
    @items_acc= Item.where( status: 1 ).paginate page: params[:page_acc], order: 'created_at desc',
    per_page: 30
    @items_nacc= Item.where( status: 0 ).paginate page: params[:page_nacc], order: 'created_at desc',
    per_page: 30

    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
      flash[:notice] = "Заказ успешно удален."
      redirect_to admin_items_url
  end
  
   def status # Подтверждение заказа
     @item = Item.find(params[:id])
     respond_to do |format|
       @item.update_attributes( status: 1 )
        Order.find(@item.order.id).items.each do |ord_it| # Циклическая проверка статуса Items
          if ord_it.status > 0       # Если все Items = 1 то и order.status = 1
            @item.order.status = 1
          else 
            @item.order.status = 0                         # Если нет, то  order.status = 0
            break
          end 
        end
        order_val( @item.order ) 
        @item.order.save
        format.html { redirect_to list_confirm_admin_items_url, notice: 'Статус заказа успешно обновлен.' }
        format.json { head :no_content }
      end      
  end

  def pay_for_override # Принудительная оплата заказа
    @item = Item.find(params[:id])
    if @item.status<2 
    @item.order.update_attributes( status: 2 ) 
    order = Order.find( @item.order.id )
          order.items.each do |item|  
          item.update_attributes( status: 2, value_total: price( item, item.order.user )[:val] )
        end
        @item.order.user.update_attributes( balance: @item.order.user.balance - @item.order.order_value )
        redirect_to admin_items_url, notice: 'Статус заказа успешно обновлен.'
    else 
      redirect_to admin_items_url, notice: 'Как-то странно оплачивать дважды...'
    end 
  end
  
  def list_pay
    @items_for_pay =  Item.where( status: 2 ).paginate page: params[:page_items], order: 'created_at desc',
    per_page: 1
    respond_to do |format|
      format.html
      format.js
    end
  end   
  
  def list_confirm
    @items_for_confirm =  Item.where( status: 0 ).paginate page: params[:page], order: 'created_at desc',
    per_page: 1
    respond_to do |format|
      format.html
      format.js
    end
  end   
  
  def edit
    @item = Item.find(params[:id])
    respond_to do |format|
    format.html 
    format.js
    end
  end
  
   def update #!!! Проверить!!! Метод не используется
     @item = Item.find(params[:id])

     @item.update_attributes(params[:item]) 
     respond_with @item
     redirect_to list_pay_admin_items_url, notice: 'Как-то странно оплачивать дважды...'  
   end
    
  
  def payd                      # Изменение статуса Item на "7" - выкуплен
    respond_to do |format|
      @item = Item.find(params[:id])
      @item.update_attributes( status: 7 )
      @item.order.update_attributes( status: 7 )
      format.html { redirect_to list_pay_admin_items_url, notice: 'Заказ успешно выкуплен.' }
      format.json { head :no_content }       
    end 
  end
  
  def cancel                       # Отклонение оплаченного заказа
    @item = Item.find(params[:id])
    respond_to do |format|
        if @item.status == 2 || 7
              @item.order.user.update_attributes( balance: (@item.order.user.balance + (@item.value_total) ) )           
              AdminNotify.cancel_delivery(@item).deliver
              @item.update_attributes( status: 9, value: 0, value_total: 0 )
              @item.order.save  
              order_val( @item.order )
              if @item.status == 2
                format.html { redirect_to list_pay_admin_items_url, notice: 'Статус заказа успешно обновлен.' }
                format.json { head :no_content }
              else
                format.html { redirect_to items_url, notice: 'Статус заказа успешно обновлен.' }
                format.json { head :no_content }
              end
              
        else
           @item.update_attributes( status: 9, value: 0, value_total: 0 )
           @item.order.save  
           format.html { redirect_to list_confirm_admin_items_url, notice: 'Статус заказа успешно обновлен.' }
           format.json { head :no_content }       
        end
    end
  end

  def re_check                       # Отправка заказа на повторную проверку
    @item = Item.find(params[:id])
    respond_to do |format|
        if @item.status == 2
              @item.order.user.update_attributes( balance: (@item.order.user.balance + (@item.value_total) ) )
              @item.update_attributes( status: 0, value_total: 0 )
              order_val( @item.order )
              @item.order.save
              format.html { redirect_to list_pay_admin_items_url, notice: 'Статус заказа успешно обновлен.' }
              format.json { head :no_content }       
        end
    end
  end

  def list_payments
    @list_payments_all =  Payment.paginate page: params[:page_payments_all], order: 'created_at desc',
    per_page: 30
    @list_payments_nacc =  Payment.where( status: [ 0 ] ).paginate page: params[:page_payments_nacc], order: 'created_at desc',
    per_page: 30
    @list_payments_problem =  Payment.where( status: [ 2 ] ).paginate page: params[:page_payments_problem], order: 'created_at desc',
    per_page: 30
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def list_lotts
    @list_lotts =  Lott.where( status: 0 ).paginate page: params[:page_lotts], order: 'lot_number desc',
    per_page: 30
    respond_to do |format|
      format.html
      format.js
    end
  end
  def list_lotts_all
    @list_lotts =  Lott.paginate page: params[:page_lotts], order: 'created_at desc',
    per_page: 30
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def list_items
    @items =  Item.where( 'status = ? AND order_no IS ? ', 7, nil ).paginate page: params[:page_items], order: 'Updated_at desc',
    per_page: 60
    respond_to do |format|
      format.html
      format.js
    end
  end   
  
  def na_sklade # Заказ поступил на склад
    @item = Item.find(params[:id])
    @item.update_attributes( status: 8 )
    AdminNotify.nasklade(@item).deliver
    redirect_to items_url, notice: 'Статус заказа успешно обновлен.'
  end
  
  def user_search # Поиск пользователя
    @user = User.usearch(params[:search])
      respond_to do |format|
        format.html
        format.js
      end
  end
  def user_card # Карточка пользователя
    @user = User.find(params[:id])
    #************************ Определение переменных для вкладок
    @user_payments = @user.payments.paginate page: params[:payments_param], order: 'created_at desc',
    per_page: 20
    @user_items = @user.orders.paginate page: params[:items_param], order: 'created_at desc',
    per_page: 20
    @user_lotts = @user.lotts.paginate page: params[:page_param], order: 'created_at desc',
    per_page: 20
    #************************ 
    
    #************************ Подсчет итоговых значений
    @user_payments_total = @user_orders_total = @user_lotts_total = 0
    @user.payments.where( status: 1 ).each do |user_total| 
      @user_payments_total += user_total.value
    end
    # where(['user_id = ? AND author_id <> ?', current_user.id, current_user.id])
    @user.orders.where([ 'status <> ? AND status <> ? AND status <> ? ', 0, 1, 9 ] ).each do |order_total| 
      @user_orders_total += order_total.order_value
    end
    @user.lotts.where([ 'status <> ? AND status <> ? AND status <> ? ', 0, 1, 9 ] ).each do |lotts_total| 
      @user_lotts_total += lotts_total.value
    end
      respond_to do |format|
          format.html
          format.js
    end
   end
end 
  

app/helpers/admin_items_helper.rb
# -*- encoding : utf-8 -*-
module AdminItemsHelper
end

app/views/admin_items/_edit.html.erb
<h1>Body edit.html.erb</h1>
jhjlkhjlkhljh <br/>
lkjhlkjdslkfjsad <br/>
sdaf;lksdf;kdsaf <br/>

app/views/admin_items/_items.html.erb
<div class = flickr_pagination >
          <%= will_paginate user_items, param_name: page_param , container: false %>
</div>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Фото</th>
      <th>Наименование</th>
      <th>Сумма</th>
      <th>Статус</th>
      
    </tr>
  </thead>
  <tbody>
    <% user_items.each do |order| %>
      <tr bgcolor="#EDEDED">
        <td><i class="icon-hand-right"></i></td>
        <td>Заказ № <%= link_to order.id, order_path(order)%></td> 
        <td>от <%= l order.created_at, format: :short  %></td> 
        <td>Итого: <strong><%=order.order_value%></strong></td> 
        <td><%=order_stat(order.status)%></td><td></td>
      
          <% order.items.each do |items| %>
            <tr>
              <td>
                <small> ID<%= items.id %> </small>
              </td> 
              <td>
                                  
                <a class="pull-left" href="#">
                <%= link_to image_tag(items.img, size: "50x50"), order_path(order)  %>
                </a>
               <div style="width:150px;">
                 <small>
                   Размер: <%= items.size %> <br/>
                   Цвет: <%= items.color %> 
                 </small>
              
               </div>
               </td> 
              <td width = '35%'><%= link_to items.name, items.link %></td>
              <td>
                <strong>$<%= items.value %></strong><br/>
                <small><%= price(items, items.order.user )[:str] %></small> <br/>
                <span class='total_price'><%= price(items, items.order.user)[:val] %> руб РФ</span> <br/>
              </td>
              <td><%= order_stat(items.status)  %></td>
              <td>
              </td>
            </tr>
              <% end %>
           
      </tr>
    <% end %>
  </tbody>
</table>

<div class = flickr_pagination >
          <%= will_paginate user_items, param_name: page_param , container: false %>
</div>

app/views/admin_items/_list_items.html.erb
<div class = flickr_pagination >
          <%= will_paginate items, param_name: page_param, container: false %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th></th>
      <th>Дата</th>
      <th>Сумма</th>
      <th>№ Заказа</th>
    </tr>
  </thead>
  <tbody>
     <% items.each do |item| %>
        <tr>
        <td><%= link_to item.id, item_path(item) %></td>
         <td>
                <a class="pull-left" href="#">
                <%= link_to image_tag(item.img, size: "50x50"), item.link  %>
                </a>
               <div style="width:100px;">
                 <small>
                   Размер: <%= item.size %> <br/>
                   Цвет: <%= item.color %> 
                 </small>
              
               </div>
               </td> 
              <td>
                <%= l item.created_at, format: :short %><br/>
              </td>
        <td>
          <h4><strong><%= item.count %> x</strong></h4>
          <h3><strong>$<%= best_in_place item, :value %></strong></h3><br/>
 
        </td>
          <td><%= best_in_place item, :order_no %></td>
        </tr>
    <% end %>
   </tbody>
</table>

<div class = flickr_pagination >
          <%= will_paginate items, param_name: page_param , container: false %>
</div>

app/views/admin_items/_payments.html.erb
<div class = flickr_pagination >
          <%= will_paginate user_payments, param_name: page_param , container: false %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Статус</th>
      <th>Дата</th>
      <th>Время</th>
      <th>Сумма</th>
      <th>Комментарий</th>
    </tr>
  </thead>
  <tbody>
    <% user_payments.each do |payment| %>
      <tr>
        <td><%= payment.id %></td>
        <td><%= stat (payment.status)  %>    </td>
        <td><%= l payment.data, format: :dt %></td>
        <td><%= l payment.time, format: :tm %></td>
        <td><span class="price"><%= number_to_currency(payment.value) %></span></td>
        <td width = '40%'><%= payment.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class = flickr_pagination >
          <%= will_paginate user_payments, param_name: page_param , container: false %>
</div>

app/views/admin_items/edit.html.erb
<h1>Body _edit.html.erb</h1>


<%= form_for(@item) do |f| %>
<%= render 'shared/error_messages',  error: @item  %>
<div class="span6 offset3">

    <%= f.label :value, 'Стоимость товара:'%>
    <%= f.text_field :value, class: 'input-small'  %> </br>
    <%= f.submit "Сохранить изменение" , class: "btn btn-large btn-primary" %><br />
 
</div>

<% end %>

app/views/admin_items/list_confirm.js.erb
$('#items_confirm').html('<%=escape_javascript(render(:partial => "list_pay", 
  locals: { items: @items_for_confirm, page_param: 'page'  }))%>');

$('.flickr_pagination a').attr('data-remote', 'true');

app/views/admin_items/list_lotts_all.html.erb
<h1>ЛОТЫ на согласование:</h1>

  <div id="lotts">
    <%= render partial: 'list_lotts', locals: { lotts: @list_lotts, page_param: 'page_lotts' } %>
  </div>

<script type="text/javascript">
  $(function() {
    $('.flickr_pagination a').attr('data-remote', 'true');
  });
</script>

app/views/admin_items/list_lotts_all.js.erb
$('#lotts').html('<%=escape_javascript(render(:partial => "list_lotts", 
  locals: { lotts: @list_lotts, page_param: 'page_lotts'  }))%>');

$('.flickr_pagination a').attr('data-remote', 'true');

app/views/admin_items/list_pay.js.erb
$('#items').html('<%=escape_javascript(render(:partial => "list_pay", 
  locals: { items: @items_for_pay, page_param: 'page_items'  }))%>');

$('.flickr_pagination a').attr('data-remote', 'true');

app/views/admin_items/list_payments.html.erb
<h1>Оплаты на согласование:</h1>

<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#pane1" data-toggle="tab">На согласовании</a></li>
    <li><a href="#pane2" data-toggle="tab">Проблемные</a></li>
    <li><a href="#pane3" data-toggle="tab">Все платежи</a></li>
  </ul>
  <div class="tab-content">
    <div id="pane1" class="tab-pane active">

      <div id="payments_nacc">
          <%= render partial: 'list_payments', locals: { payments: @list_payments_nacc, page_param: 'page_payments_nacc' } %>
      </div>
    </div>
    
    <div id="pane2" class="tab-pane">
       
      <div id="payments_problem">
          <%= render partial: 'list_payments', locals: { payments: @list_payments_problem, page_param: 'page_payments_problem' } %>
      </div>
   
    </div>
    <div id="pane3" class="tab-pane">
      <div id="payments_all">
          <%= render partial: 'list_payments', locals: { payments: @list_payments_all, page_param: 'page_payments_all' } %>
      </div>
    </div>
  </div><!-- /.tab-content -->
</div><!-- /.tabbable -->


<script type="text/javascript">
  $(function() {
    $('.flickr_pagination a').attr('data-remote', 'true');
  });
</script>

app/views/admin_items/list_payments.js.erb
$('#payments_nacc').html('<%=escape_javascript(render(:partial => "list_payments", 
  locals: { payments: @list_payments_nacc, page_param: 'page_payments_nacc'  }))%>');
$('#payments_problem').html('<%=escape_javascript(render(:partial => "list_payments", 
  locals: { payments: @list_payments_problem, page_param: 'page_payments_problem'  }))%>');
$('#payments_all').html('<%=escape_javascript(render(:partial => "list_payments", 
  locals: { payments: @list_payments_all, page_param: 'page_payments_all'  }))%>');

$('.flickr_pagination a').attr('data-remote', 'true');

app/views/admin_items/user_card.html.erb
<br/>
<h2>Страница пользователя <%= @user.nik %> </h2>
Город: <b><%= @user.configApp.city %></b>, Курс 1 доллар = <%= @user.configApp.rate %> <%= @user.configApp.currency %>  <br>
Баланс: <%= @user.balance %> | Вычесленный:
<%= @user_payments_total.round( 2 ) - @user_lotts_total.round( 2 ) - @user_orders_total.round( 2 ) %><br/>
Всего пополнений: <b><%= @user_payments_total.round( 2 ) %></b> | Всего заказов: <b><%= @user_orders_total.round( 2 ) %></b>
 | Всего лотов: <b><%= @user_lotts_total.round( 2 ) %></b> <br/>
Итого потрачено: <%= @user_lotts_total.round( 2 ) + @user_orders_total.round( 2 ) %> <br/>
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#pane1" data-toggle="tab">Пополнения</a></li>
    <li><a href="#pane2" data-toggle="tab">Заказы</a></li>
    <li><a href="#pane3" data-toggle="tab">Лоты</a></li>
  </ul>
  <div class="tab-content">
    <div id="pane1" class="tab-pane active">
      <div id="payments">
        <%= render partial: 'payments', locals: { user_payments: @user_payments, page_param: 'payments_param' } %>
      </div>
      
    </div>
    <div id="pane2" class="tab-pane">
       
      <div id="items">
        <%= render partial: 'items', locals: { user_items: @user_items, page_param: 'items_param' } %>
      </div>
    </div>
    <div id="pane3" class="tab-pane">
      <div id="lotts">
        <%= render partial: 'list_lotts', locals: { lotts: @user_lotts, page_param: 'page_param' } %>
      </div>
    </div>
  </div><!-- /.tab-content -->
</div><!-- /.tabbable -->



<script type="text/javascript">
  $(function() {
    $('.flickr_pagination a').attr('data-remote', 'true');
  });
</script>
  

app/views/admin_items/user_card.js.erb
$('#payments').html('<%=escape_javascript(render(:partial => "payments", locals: { user_payments: @user_payments, page_param: 'payments_param' }))%>');
$('#items').html('<%=escape_javascript(render(:partial => "items", locals: { user_items: @user_items, page_param: 'items_param' }))%>');
$('#lotts').html('<%=escape_javascript(render(:partial => "list_lotts", locals: { lotts: @user_lotts, page_param: 'page_param' }))%>');

$('.flickr_pagination a').attr('data-remote', 'true');

app/views/admin_items/user_search.html.erb
<h1>Поиск по пользователю:</h1>

<%= form_tag user_search_admin_items_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-large btn-primary" %>
  </p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Ник</th>
      <th>E-mail</th>
      <th>Баланс</th>
    </tr>
  </thead>
  <tbody>
     <% @user.each do |user| %>
        <tr>
          <td><i class="icon-user"></i><%= link_to user.nik, user_card_admin_item_path( user ) %></td>
          <td><%= user.email %></td>
          <td><%= user.balance %></td> 
        </tr>
    <% end %>
   </tbody>
</table>