config/routes.rb
TestApp::Application.routes.draw do

  resources :catalogs do
    get :show_catalog, on: :collection
    get :show_catalog_first, on: :collection
  end 

  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show] 
    end
    root :to => 'categories#index', :via => :get
  end
  resources :lotadmin do
    get :lot_for_confirm, on: :collection
    get :confirmed, on: :member
  end 

  devise_for :users
  get "summury/totals"
  get "static_pages/faq"
  get "static_pages/about"
  get "static_pages/contacts"
  get "help", to: "static_pages#help"
  root to: 'StaticPages#about'
  resources :lotts do
    get :status, on: :member
  end
  resources :products
  resources :summury do
      get :totals, on: :member
      get :dolzhnik_notify, on: :member
  end 
  resources :users
  resources :orders do
    get :pay_for, on: :member
  end 
  resources :items
  resources :config_apps
  resources :payments do
    get :status, on: :member
    get :status_problem, on: :member
  end 
  resources :purchases
  resources :admin_items do
    get :status, on: :member
    get :payd, on: :member
    get :cancel, on: :member
    get :pay_for_override, on: :member
    get :na_sklade, on: :member
    get :list_pay, on: :collection  
    get :list_confirm, on: :collection
    get :list_payments, on: :collection
    get :list_lotts, on: :collection
    get :list_lotts_all, on: :collection
    get :list_items, on: :collection
    get :re_check, on: :member
    get :user_search, on: :collection
    get :user_card, on: :member
  end
  resources :lots do
    get :book, on: :member  
    get :debook, on: :member
  end 
  

end

app/models/lot.rb
# == Schema Information
#
# Table name: lots
#
#  id          :integer          not null, primary key
#  value       :decimal(6, 2)    not null
#  link        :string(255)      not null
#  name        :string(255)      not null
#  seller_rate :string(255)      default("0"), not null
#  img         :string(255)      not null
#  color       :string(255)
#  catalog_id  :integer
#  topic_id    :integer
#  moderator   :integer
#  processing  :integer
#  annotation  :text
#  status      :integer          default(0), not null
#  orderno     :string(255)
#  track       :string(255)
#  havy        :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

# -*- encoding : utf-8 -*-
class Lot < ActiveRecord::Base
  attr_accessible :value, :link, :name, :seller_rate, :img, :color, :annotation, :status, 
  :orderno, :track, :havy, :lotitems_attributes, :processing, :moderator, :topic_id, :catalog_id
  has_many :lotitems, :dependent => :destroy
  has_one :topic
  accepts_nested_attributes_for :lotitems,  :allow_destroy => true
  validates :link, presence: true
  validates :name, presence: true
  validates_length_of :name, maximum: 55
  validates :catalog_id, presence: true
  validates :seller_rate, presence: true
  validates :img, presence: true
  validates :value, presence: true
  validates_numericality_of :value, greater_than_or_equal_to: 0, message: 'Сумма - только цифры, разделитель - точка, например: 288.80' 
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
    include ApplicationHelper
  def new
    @lot = Lot.new
    @lot.lotitems.build
  end
  
  def create
    
    @lot = Lot.new( params[:lot] )
    @lot.moderator = current_user.id
    
    @forum = Forum.find( 1 )  # Создаем новый топик на форуме id=1
    @topic = @forum.topics.build( title: @lot.name , body: 'Автоматически созданный топик'  )
    @topic.user = current_user
    @topic.save
    @lot.topic_id = @topic.id
    
    if @lot.save
         redirect_to @lot, notice: 'Ваш лот успешно добавлен и ожидает подтверждения.' 
      else
         render action: "new" 
      end
    end  
  
  def show
    @lot = Lot.find(params[:id])
    @topic = Topic.find( @lot.topic_id )
    
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lot }
    end
  end
  
  def edit
    @lot = Lot.find(params[:id])
  end
  
  def update
    @lot = Lot.find(params[:id])

    respond_to do |format|
      if @lot.update_attributes(params[:lot])
        format.html { redirect_to @lot, notice: 'Сборный лот успешно обновлен!.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
      @lot = Lot.find(params[:id])
      @topic = Topic.find( @lot.topic_id)
      @topic.destroy
      @lot.destroy
      
      flash[:notice] = "Заказ успешно удален."
      redirect_to lots_url
  end

  
  def book
    @lotitem = Lotitem.find(params[:l_param])
    t=params[:lotitem]
    sts = 1
    @lotitem.update_attributes( user_id: current_user.id, color: t[:color], comment: t[:comment], status: 3 )
    @lotitem.lot.lotitems.each  do |item| 
      if item.status == 3 
        sts = 3
      else
        sts = 1
        break
      end
    end
    @lotitem.lot.update_attributes( status: sts )   
    redirect_to @lotitem.lot, notice: 'Бронирование выполненно успешно!' 
  end 
  
  def debook
    sts = 1
    @lotitem = Lotitem.find(params[:l_param])
    @lotitem.update_attributes( user_id: 0, color: nil, comment: nil, status: 1 ) 
       @lotitem.lot.lotitems.each  do |item| 
      if item.status == 3 
        sts = 3
      else
        sts = 1
        break
      end
    end
    @lotitem.lot.update_attributes( status: sts ) 
    redirect_to @lotitem.lot, notice: 'Бронирование аннулированно.' 
  end 
  
  
end

app/helpers/lots_helper.rb
module LotsHelper
  def find_user( user )
    User.find( user ).nik
  end
  
  def lot_price( lot, user ) 
    total = 0
    pcn = 0.1 # Стандартный процент 10%
    cfc = 1 # стандартный коэффициент для лотов дешевле 10 долларов - 1 доллар
    if lot.moderator == user.id
      pcn = 0.05
      cfc = 0.5
    end
      
    if user.configApp.id < 2
# --- Расчет для Приднестровья ------
          if lot.value < 10 
            total = ( lot.value + cfc )*user.configApp.rate
          else # если лот дороже 10 долларов
            if lot.havy
              total = ( lot.value + lot.value*pcn*2 )*user.configApp.rate
            else 
              total = ( lot.value + lot.value*pcn )*user.configApp.rate
            end
          end
    else
# --- Расчет для Одессы ------      
      total = ( lot.value + lot.value*pcn )*user.configApp.rate
    end
  end
  def total_lot_price( lot, user )
    total = 0
    for l in lot.lotitems do
      if user.id == l.user_id
        total = total + l.value_total
      end
    end
     total
  end

  def cat_path
      a = Catalogitem.where( id: @lot.catalog_id ).first.catalog.title
      b = Catalogitem.where( id: @lot.catalog_id ).first.line 
      c = a + ' > ' + b
  end
   
    
end

app/views/lots/_dialog.html.erb
<p>
  <%= form_for(lotitempartial, url: {:action => 'book', :controller => 'lots'}, method: :get) do |f| %>
      
          <%= hidden_field_tag(:l_param, lotitempartial.id) %>
          <%= f.label :color, 'Цвет'%>
          <%= f.text_field :color, placeholder: "Вносить при необходимости..." %>
      
          <%= f.label :comment, 'Комментарий'%>
          <%= f.text_field :comment, placeholder: "Коментарий при необходимости..." %>
<br>      
          <%= f.submit "Забронировать" , class: "btn btn-large btn-primary" %>          
<% end %>
</p>

app/views/lots/_form.html.erb
  <div class="row">
  <div class="span6">
  <%= nested_form_for(@lot) do |f| %>
      <%= render 'shared/error_messages',  error: @lot  %>

          <%= f.label :name, 'Наименование лота:'%>
          <%= f.text_field :name %>
    
          <%= f.label :catalog_id, "Выберите каталог"%>  
          <%= f.grouped_collection_select :catalog_id,
          Catalog.all, :catalogitems, :title, :id, :line, { :prompt => 'Выберите раздел каталога ...' }
          %>
              
          <%= f.label :value, 'Стоимость позиции лота, в USD:'%>
          <%= f.text_field :value %>
      
          <%= f.label :color, 'Цвет:'%>
          <%= f.text_field :color %>
        
          <%= f.label :havy, 'Объемный?', :value => "false"%>
          <%= f.radio_button :havy, false, :checked => true %> Нет
          <%= f.radio_button :havy, true  %> Да <br><br>
        
          <%= f.label :link, 'Ссылка на страницу лота:'%>
          <%= f.text_field :link %>
         
          <%= f.label :img, 'Ссылка на картинку:'%>
          <%= f.text_field :img %>    
        
          <%= f.label :seller_rate, 'Ссылка на рейтинг продавца:'%>
          <%= f.text_field :seller_rate %>

          <%= f.label :processing, 'Время обработки заказа продавцом, дней:'%>
          <%= f.text_field :processing %>
          
          <%= f.label :annotation, 'Коментарий:'%>
          <%= f.text_area :annotation, placeholder: "В случае необходимости укажите Ваш коментарий (не обязательно)...",
            rows: "5" %>
    
          <%= f.fields_for :lotitems do |lotItems_form| %>
              <div class="row">
              <div class="span3">
              <%= render partial: 'lot_items_fields', :locals => { :f => lotItems_form } %>
              <%= lotItems_form.link_to_remove "Удалить эту позицию" %>
             </div>
             </div>         
          <% end %>
          <%= f.link_to_add "Добавить еще одну позицию", :lotitems %>
          
             <br>
             <%= f.submit "Оформить лот" , class: "btn btn-large btn-primary" %>
  <% end %>       
  </div> 

  </div>

  

app/views/lots/_lot_items_fields.html.erb
      <%= f.label :item, 'Наименование позиции лота:'%>
      <%= f.text_field :item %>

app/views/lots/_lot_users.html.erb
<span class="user_lst">
<b>Участники лота:</b><br>
  <% @lot.lotitems.each do |lotitem| %>
    <!-- Modal -->
<div class="modal fade" id='<%= lotitem.id %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title" id="myModalLabel">Забронировать <%= lotitem.item %> </h4>
	        <%= lotitem.lot.name %>
	      </div>
      <div class="modal-body">
         <%= lotitem.item %>
        <%= render partial: 'dialog', locals: { lotitempartial: lotitem } %>
      </div>
    </div>
  </div>
</div>
      <!-- <%= order_stat( lotitem.status ) %> -->
      <% if lotitem.user_id == 0 %>
 <span class="btn btn-mini" data-toggle="modal" data-target='#<%= lotitem.id %>'> Бронь </span>


          <b><%= lotitem.item %></b> 
          Свободно<br> 
      <% else %>
        <%= link_to 'Снять', debook_lot_path( l_param: lotitem.id ), :class => 'btn btn-mini btn-danger ' %> 
        <b><%= lotitem.item %></b> 
        <span class="green"><%= lotitem.user.nik %>  <%= lotitem.color %>  <%= lotitem.comment %></span><br>
      <% end %>
  <% end %>
 
  <span class="lot_total">
    У Вас бронь на:  <%= total_lot_price( @lot, current_user )  %> 
    <%= current_user.configApp.currency  %>
  </span> 
</span>

app/views/lots/_modal.html.erb
<div class="modal fade" id="addBookDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>

      
      <div class="modal-body">
        <input type="text" name="bookId" id="bookId" value="" />
      </div>

      
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
$(document).on("click", ".open-AddBookDialog", function (e) {

	e.preventDefault();

	var _self = $(this);

	var myBookId = _self.data('id');
	$("#bookId").val(myBookId);

	$(_self.attr('href')).modal('show');
});
</script>

app/views/lots/_social.html.erb
<script type="text/javascript">(function() {
  if (window.pluso)if (typeof window.pluso.start == "function") return;
  if (window.ifpluso==undefined) { window.ifpluso = 1;
    var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
    s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
    s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
    var h=d[g]('body')[0];
    h.appendChild(s);
  }})();</script>
<div class="pluso" data-background="none;" data-options="small,square,line,horizontal,counter,sepcounter=1,theme=14" data-services="odnoklassniki,vkontakte,facebook,moimir"></div>

app/views/lots/edit.html.erb
<h1>Изменить лот:</h1>

<%= render 'form' %>

<%= link_to 'Просмотреть', @catalog %> |
<%= link_to 'Назад', catalogs_path %>

app/views/lots/new.html.erb
<h1>Создать новый лот</h1>

<%= render 'form' %>

app/views/lots/show.html.erb
  <div class="row">
  <div class="span3">
    <br><h2> ЛОТ № <%= @lot.id %> </h2>
    <%= link_to image_tag(@lot.img, size: "250x250", class: "img-polaroid"), @lot.link, target: '_blank'  %><br>
    <small><%= cat_path %></small><br><br>
    Цвет: <b><%= @lot.color %></b>
    <div Style='line-height:10pt'>
      <small><br>
          <i class="icon-info-sign"></i> Цвет или оттенок изделия на фотографии может отличаться от реального. 
          Характеристики и комплектация товара могут изменятся производителем без уведомления. 
          Kupibazar.com не несет ответственности за изменения внесенные производителем.
      </small>
    </div>  
    <br><i class="icon-signal"></i><b> Рейтинг продавца: <%= image_tag( @lot.seller_rate ) %> </b><br>
    <b><i class="icon-user"></i> Модератор лота: <%=  find_user( @lot.moderator ) %> </b><br><br>
      
    <br>
        <%= render 'social' %> <!-- Share Button -->

    </div>  
  <div class="span9">  
  <br><h2><%= @lot.name %> </h2>
    <div class="row">
      <div class="span4">
        <span class="price_local">
          <%= lot_price( @lot, current_user ) %> <span class="price_cur"><%= current_user.configApp.currency  %></span><br>
        </span>
        <span class="price_usd">
          <%= @lot.value %> $<br>
        </span>
          <% if @lot.moderator == current_user.id %>
            <small><i class="icon-info-sign"></i> Для Вас, как для модератора этого лота, <br>
              указана цена с учетом скидки 50% на коммиссию</small><br> 
        <% end %>
        <br>
         <i class="icon-time"></i>
          Время обработки заказа <br>продавцом (дней): <b><%= @lot.processing %></b> 
        <br>
        <br><%= order_stat( @lot.status ) %>
        <br><%= @lot.annotation %>
      </div>
      <% if @lot.status > 0 %>
      <div class="span5">
        <%= render 'lot_users' %>
      </div>
      <% end %>
    </div>

  <% if @lot.status < 1 %>


  <% end %>
  </div>
  </div>
  <br><br><br>
  <p>
    <%= link_to "Изменить", edit_lot_path(@lot) %> |
    <%= link_to "Удалить", @lot, :confirm => 'Are you sure?', :method => :delete %> |
    <%= link_to "Просмотреть все заказы", @lot %>
  </p>

<!-- ---------------- FORUM ----------------------------- -->
<div class="module">
  <div class="module_header">
    <%= @topic.title %>
  </div>
  <div>
    <table class="tablef">
      <% @topic.posts.each do |post| %>
      <tr>
        <td class="post_author" class="tablef" rowspan="2">
          <span class="name"><%= post.user.nik %></span>
          <span class="avatar"><!-- This space reserved for Avatar --></span>
          <span class="info smaller">
            Постов: <%= post.user.posts.size %><br />
            Зарегистрирован(а): <%= post.user.created_at.to_s(:joined) %><br />
          </span>
        </td>
        <td class="post_header" class="tablef">
          <span class="left post_date smaller"><small>Написано <%= post.created_at %></small></span>
          <span class="right controls">
            <%= link_to "Написать", new_topic_post_path(@topic) %>
            <%= link_to "Цитировать", new_topic_post_path(@topic, :quote => post) %>
            <%= link_to "Редактировать", edit_post_path(post) %>
            <%= link_to "Удалить", post, :confirm => "Are you sure?", :method => :delete %>
          </span>
        </td>
      </tr>
      <tr class="tablef">
        <td class="tablef" class="post_body">
          <%= simple_format(auto_link(post.body)) %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<span id="end"></span>